import type { Conversation, Job, Post, User } from "@/types";

export const CURRENT_USER_ID = "user-1";

export const currentUser: User = {
  id: CURRENT_USER_ID,
  name: "Ana Paula Mendes",
  headline: "Gerente de RH | Especialista em Gestão de Pessoas",
  avatar: "AP",
  role: "recrutador",
  company: "Launch",
  location: "São Paulo, SP",
  connections: 847,
  about: "Profissional de RH com mais de 10 anos de experiência em recrutamento, desenvolvimento organizacional e gestão de talentos.",
  skills: [
    "Recrutamento",
    "Gestão de Pessoas",
    "Employer Branding",
    "People Analytics",
    "Treinamento",
    "Entrevistas",
    "Seleção de Talentos"
  ],
  education: "MBA em Gestão de Pessoas",
  experience: "10 anos atuando em RH e recrutamento.",
  certifications: ["People Analytics", "LinkedIn Recruiter"],
  languages: ["Português", "Inglês"],
  linkedin: "linkedin.com/in/anapaulamendes",
  github: "github.com/anapaulamendes",
  portfolio: "anapaulamendes.com.br",
  desiredPosition: "Gerente de RH",
  salaryExpectation: "R$ 15.000",
  birthDate: "1988-03-20",
  maritalStatus: "Casada",
  courses: ["Gestão Estratégica de Pessoas", "People Analytics", "Liderança Corporativa"],
  achievements: [
    "Redução de turnover em 35%",
    "Implantação de RH Digital",
    "Criação de programa de liderança"
  ],
  online: true,
  email: "ana.mendes@launchrh.com.br",
  phone: "(11) 98765-4321",
  whatsapp: "11987654321",
};

export const users: User[] = [
  currentUser,
  {
    id: "user-2",
    name: "Carlos Eduardo Silva",
    headline: "Desenvolvedor Full Stack | React & Node.js",
    avatar: "CS",
    role: "candidato",
    location: "Campinas, SP",
    connections: 523,
    about: "Desenvolvedor Full Stack com 5 anos de experiência em aplicações web escaláveis, APIs REST e microsserviços.",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "SQL",
      "NoSQL",
      "PostgreSQL",
      "MongoDB",
      "Docker",
      "CI/CD",
      "AWS"
    ],
    education: "Bacharel em Ciência da Computação - UNICAMP",
    experience: "Experiência em Tech Solutions e Digital Systems, liderando equipes e criando plataformas para milhares de usuários.",
    certifications: ["AWS Cloud Practitioner", "Scrum Foundation", "Docker Essentials", "Node.js Advanced"],
    languages: ["Português - Nativo", "Inglês - Avançado", "Espanhol - Intermediário"],
    linkedin: "linkedin.com/in/carloseduardo",
    github: "github.com/carloseduardo",
    portfolio: "carloseduardo.dev",
    desiredPosition: "Desenvolvedor Full Stack Senior",
    salaryExpectation: "R$ 12.000 a R$ 15.000",
    birthDate: "1995-05-10",
    maritalStatus: "Solteiro",
    courses: ["Docker Completo", "Kubernetes Essentials", "Arquitetura de Microsserviços", "React Avançado"],
    achievements: [
      "Migração para microsserviços",
      "Redução de custos AWS em 35%",
      "Pipeline CI/CD automatizada"
    ],
    online: true,
    email: "carlos.silva@email.com",
    phone: "(19) 99876-5432",
    whatsapp: "19998765432",
  },
  {
    id: "user-3",
    name: "Mariana Costa",
    headline: "Especialista em Marketing Digital | Growth Marketing | SEO",
    avatar: "MC",
    role: "candidato",
    location: "Rio de Janeiro, RJ",
    connections: 312,
    about: "Profissional de Marketing Digital com 4 anos de experiência em SEO, mídia paga e growth hacking.",
    skills: [
      "SEO",
      "Google Ads",
      "Meta Ads",
      "Social Media",
      "Analytics",
      "Copywriting",
      "Growth Marketing",
      "Email Marketing",
      "Inbound Marketing"
    ],
    education: "Graduação em Marketing - UFRJ",
    experience: "Experiência em startups com foco em geração de leads e aumento de conversão.",
    certifications: ["Google Ads", "Google Analytics", "HubSpot Inbound", "Meta Media Buying"],
    languages: ["Português - Nativo", "Inglês - Intermediário", "Espanhol - Básico"],
    linkedin: "linkedin.com/in/marianacosta",
    portfolio: "marianacosta.com.br",
    desiredPosition: "Especialista em Marketing Digital",
    salaryExpectation: "R$ 8.000 a R$ 10.000",
    birthDate: "1997-08-14",
    maritalStatus: "Solteira",
    courses: ["SEO Avançado", "Growth Marketing", "Google Ads Expert"],
    achievements: ["Aumento de 300% no tráfego orgânico", "Gestão de R$ 1 milhão em mídia paga"],
    online: false,
    email: "mariana.costa@email.com",
    phone: "(21) 97654-3210",
    whatsapp: "21976543210",
  },
  {
    id: "user-4",
    name: "Roberto Almeida",
    headline: "Diretor Comercial | Executivo de Vendas B2B",
    avatar: "RA",
    role: "candidato",
    location: "Belo Horizonte, MG",
    connections: 1205,
    about: "Executivo Comercial com mais de 15 anos de experiência em vendas B2B e liderança de equipes.",
    skills: [
      "Vendas B2B",
      "Negociação",
      "Gestão de Equipes",
      "CRM",
      "Planejamento Estratégico",
      "Business Development"
    ],
    education: "Bacharel em Administração - UFMG",
    experience: "Diretor Comercial em Indústria Nacional S.A. e Gerente Nacional de Vendas em Grupo Empresarial Brasil.",
    certifications: ["Gestão Comercial Avançada", "Leadership Training"],
    languages: ["Português - Nativo", "Inglês - Avançado", "Espanhol - Fluente"],
    linkedin: "linkedin.com/in/robertoalmeida",
    desiredPosition: "Diretor Comercial ou Diretor de Negócios",
    salaryExpectation: "R$ 25.000 a R$ 35.000",
    birthDate: "1982-01-12",
    maritalStatus: "Casado",
    courses: ["Liderança Executiva", "Gestão Estratégica", "Negociação Avançada"],
    achievements: ["Aumento de faturamento em 120%", "Expansão nacional", "Reconhecido como Executivo Destaque por 3 anos"],
    online: true,
    email: "roberto.almeida@email.com",
    phone: "(31) 99123-4567",
    whatsapp: "31991234567",
  },
  {
    id: "user-5",
    name: "Fernanda Oliveira",
    headline: "UX/UI Designer | Design de Produto",
    avatar: "FO",
    role: "candidato",
    location: "São Paulo, SP",
    connections: 456,
    about: "Designer com 6 anos de experiência em UX/UI, design de produto e prototipagem.",
    skills: [
      "UX Design",
      "UI Design",
      "Figma",
      "Design Thinking",
      "Prototipagem",
      "User Research",
      "Design System"
    ],
    education: "Design Gráfico - FAAP",
    experience: "UX/UI Designer em startups e empresas de tecnologia.",
    certifications: ["UX Design Professional", "Google UX Certificate"],
    languages: ["Português", "Inglês"],
    linkedin: "linkedin.com/in/fernandaoliveira",
    portfolio: "fernandadesign.com",
    desiredPosition: "UX/UI Designer Senior",
    salaryExpectation: "R$ 10.000 a R$ 12.000",
    birthDate: "1993-11-02",
    maritalStatus: "Solteira",
    courses: ["Design Thinking", "Prototipagem Avançada"],
    achievements: ["Redesign de plataforma com aumento de 50% em retenção", "Criação de design system corporativo"],
    online: true,
    email: "fernanda.oliveira@email.com",
    phone: "(11) 91234-5678",
    whatsapp: "11912345678",
  },
  {
  id: "user-6",
  name: "Juliana Martins",
  headline: "Analista de RH Júnior | Recrutamento & Seleção",
  avatar: "JM",
  role: "candidato",
  location: "São Paulo, SP",
  connections: 210,
  about: "Profissional de RH com 3 anos de experiência em recrutamento e seleção, entrevistas e integração de novos colaboradores.",
  skills: [
    "Recrutamento",
    "Seleção de Talentos",
    "Entrevistas",
    "Gestão de Pessoas",
    "Comunicação"
  ],
  education: "Graduação em Psicologia - PUC-SP",
  experience: "Analista de RH em empresas de médio porte, conduzindo processos seletivos e programas de integração.",
  certifications: ["LinkedIn Recruiter"],
  languages: ["Português", "Inglês - Básico"],
  linkedin: "linkedin.com/in/julianamartins",
  desiredPosition: "Analista de Recrutamento e Seleção",
  salaryExpectation: "R$ 5.000",
  birthDate: "1994-09-12",
  maritalStatus: "Solteira",
  courses: ["Gestão de Pessoas", "Entrevistas por Competência"],
  achievements: ["Redução de tempo médio de contratação em 25%", "Implantação de processo de onboarding estruturado"],
  online: true,
  email: "juliana.martins@email.com",
  phone: "(11) 93456-7890",
  whatsapp: "11934567890",
}
];


export const seedJobs: Job[] = [
  {
    id: "job-1",
    title: "Analista de Recrutamento e Seleção",
    company: "Launch",
    location: "São Paulo, SP",
    type: "CLT",
    modality: "Híbrido",
    salary: "R$ 4.500 - R$ 6.000",
    description: "Conduzir processos seletivos completos, da abertura da vaga à integração.",
    requirements: [
      "Recrutamento",
      "Gestão de Pessoas",
      "LinkedIn Recruiter",
      "Entrevistas",
      "Seleção de Talentos"
    ],
    benefits: ["Vale refeição", "Plano de saúde", "Home office 2x/semana", "PLR"],
    postedBy: "user-1",
    postedAt: "2026-07-07T08:00:00Z",
    applicants: 34,
  },
  {
    id: "job-2",
    title: "Desenvolvedor Full Stack",
    company: "TechCorp Brasil",
    location: "Campinas, SP",
    type: "CLT",
    modality: "Remoto",
    salary: "R$ 8.000 - R$ 12.000",
    description: "Desenvolvedor full stack para projetos com React e Node.js.",
    requirements: [
      "React",
      "Node.js",
      "TypeScript",
      "SQL",
      "NoSQL",
      "Docker",
      "CI/CD"
    ],
    benefits: ["100% remoto", "Plano de saúde premium", "Auxílio home office"],
    postedBy: "user-1",
    postedAt: "2026-07-06T12:00:00Z",
    applicants: 67,
  },
  {
    id: "job-3",
    title: "Estágio em Marketing Digital",
    company: "StartupXYZ",
    location: "Rio de Janeiro, RJ",
    type: "Estágio",
    modality: "Híbrido",
    salary: "R$ 1.500 + VT",
    description: "Estágio para estudantes de Marketing ou Comunicação.",
    requirements: [
      "SEO",
      "Google Ads",
      "Social Media",
      "Copywriting",
      "Proatividade"
    ],
    benefits: ["Mentoria semanal", "Possibilidade de efetivação"],
    postedBy: "user-1",
    postedAt: "2026-07-05T10:00:00Z",
    applicants: 89,
  },
  {
    id: "job-4",
    title: "Gerente Comercial",
    company: "Indústria Nacional SA",
    location: "Belo Horizonte, MG",
    type: "CLT",
    modality: "Presencial",
    salary: "R$ 12.000 - R$ 18.000",
    description: "Liderar equipe de 15 vendedores na região Sudeste.",
    requirements: [
      "Vendas B2B",
      "Negociação",
      "Gestão de Equipes",
      "CRM",
      "Planejamento Estratégico",
      "Business Development"
    ],
    benefits: ["Carro da empresa", "Comissão agressiva", "Previdência privada"],
    postedBy: "user-1",
    postedAt: "2026-07-04T08:00:00Z",
    applicants: 23,
  },
  {
    id: "job-5",
    title: "UX/UI Designer Senior",
    company: "DesignTech Solutions",
    location: "São Paulo, SP",
    type: "CLT",
    modality: "Híbrido",
    salary: "R$ 9.000 - R$ 12.000",
    description: "Responsável por criar experiências digitais centradas no usuário e liderar projetos de design de produto.",
    requirements: [
      "UX Design",
      "UI Design",
      "Figma",
      "Design Thinking",
      "Prototipagem",
      "User Research",
      "Design System"
    ],
    benefits: ["Vale refeição", "Plano odontológico", "Gympass", "Day off no aniversário"],
    postedBy: "user-1",
    postedAt: "2026-07-03T09:00:00Z",
    applicants: 41,
  },
  {
    id: "job-6",
    title: "Especialista em Growth Marketing",
    company: "ScaleUp Digital",
    location: "Rio de Janeiro, RJ",
    type: "CLT",
    modality: "Remoto",
    salary: "R$ 9.000 - R$ 11.000",
    description: "Planejar e executar estratégias de aquisição e retenção de clientes com foco em crescimento escalável.",
    requirements: [
      "Growth Marketing",
      "SEO",
      "Google Ads",
      "Meta Ads",
      "Inbound Marketing",
      "Analytics"
    ],
    benefits: ["100% remoto", "Plano de saúde", "Auxílio home office", "Cursos de capacitação"],
    postedBy: "user-1",
    postedAt: "2026-07-02T11:00:00Z",
    applicants: 52,
  }
];


export const seedConversations: Conversation[] = [
  {
    id: "conv-1",
    participantIds: ["user-1", "user-2"],
    lastMessageAt: "2026-07-07T15:30:00Z",
    messages: [
      { id: "msg-1", senderId: "user-2", content: "Olá Ana! Vi a vaga de Desenvolvedor Full Stack. Ainda está aberta?", timestamp: "2026-07-07T14:00:00Z", read: true },
      { id: "msg-2", senderId: "user-1", content: "Oi Carlos! Sim, a vaga continua aberta!", timestamp: "2026-07-07T14:15:00Z", read: true },
      { id: "msg-3", senderId: "user-2", content: "Gostaria de saber mais sobre o processo seletivo.", timestamp: "2026-07-07T14:20:00Z", read: true },
      { id: "msg-4", senderId: "user-1", content: "São 3 etapas: triagem, entrevista técnica e entrevista com gestor.", timestamp: "2026-07-07T15:30:00Z", read: false },
    ],
  },
  {
    id: "conv-2",
    participantIds: ["user-1", "user-3"],
    lastMessageAt: "2026-07-06T11:00:00Z",
    messages: [
      { id: "msg-5", senderId: "user-3", content: "Enviei minha candidatura para a vaga de estágio.", timestamp: "2026-07-06T10:30:00Z", read: true },
      { id: "msg-6", senderId: "user-1", content: "Recebi sua candidatura. Retorno em breve! 😊", timestamp: "2026-07-06T11:00:00Z", read: true },
    ],
  },
  {
    id: "conv-3",
    participantIds: ["user-1", "user-4"],
    lastMessageAt: "2026-07-05T16:45:00Z",
    messages: [
      { id: "msg-7", senderId: "user-4", content: "Tenho interesse na vaga de Gerente Comercial.", timestamp: "2026-07-05T16:00:00Z", read: true },
      { id: "msg-8", senderId: "user-1", content: "Sua experiência é impressionante. Vou verificar com o cliente.", timestamp: "2026-07-05T16:45:00Z", read: true },
    ],
  },
  {
    id: "conv-4",
    participantIds: ["user-1", "user-5"],
    lastMessageAt: "2026-07-03T14:20:00Z",
    messages: [
      { id: "msg-9", senderId: "user-5", content: "Olá Ana, vi a vaga de UX/UI Designer Senior. Gostaria de saber se há possibilidade de trabalho híbrido.", timestamp: "2026-07-03T14:00:00Z", read: true },
      { id: "msg-10", senderId: "user-1", content: "Sim, Fernanda! O modelo é híbrido, com 3 dias presenciais e 2 remotos.", timestamp: "2026-07-03T14:20:00Z", read: true },
    ],
  },
  {
    id: "conv-5",
    participantIds: ["user-1", "user-3"],
    lastMessageAt: "2026-07-02T12:30:00Z",
    messages: [
      { id: "msg-11", senderId: "user-3", content: "Vi a vaga de Growth Marketing. Parece alinhada ao meu perfil. Está aberta?", timestamp: "2026-07-02T12:00:00Z", read: true },
      { id: "msg-12", senderId: "user-1", content: "Está sim, Mariana! Seu perfil é bastante compatível. Vamos agendar uma entrevista inicial.", timestamp: "2026-07-02T12:30:00Z", read: true },
    ],
  }
];

export const seedPosts: Post[] = [
  {
    id: "post-1",
    authorId: "user-5",
    content:
      "🎯 Estamos expandindo nossa equipe! A Launch busca profissionais apaixonados por gestão de pessoas. Confira as vagas abertas!",
    likes: 142,
    comments: 28,
    shares: 15,
    createdAt: "2026-07-07T10:00:00Z",
    category: "noticia",
  },
  {
    id: "post-2",
    authorId: "user-1",
    content:
      "💡 Dica do dia: A retenção de talentos começa no processo seletivo.\n\n#GestãoDePessoas #RH #LaunchRH",
    likes: 89,
    comments: 12,
    shares: 34,
    createdAt: "2026-07-06T14:30:00Z",
    category: "dica",
  },
  {
    id: "post-3",
    authorId: "user-5",
    content:
      "📰 Tendências de RH para 2026:\n\n• People Analytics com IA\n• Employer Experience\n• Flexibilidade híbrida\n• Saúde mental no trabalho",
    likes: 256,
    comments: 67,
    shares: 89,
    createdAt: "2026-07-05T09:15:00Z",
    category: "artigo",
  },
  {
    id: "post-4",
    authorId: "user-1",
    content: "🎉 Parabéns à equipe Launch RH pelo excelente resultado no projeto TechCorp!",
    likes: 178,
    comments: 45,
    shares: 22,
    createdAt: "2026-07-04T16:00:00Z",
    category: "evento",
  },
];